### ISSUE TITLE
Create Customized Logo

### ISSUE THREAD

**Issue by kenju254** [GDGKenya/Solve4X#1]

**Comment by mercyorangi** [comment]
![gdg_nairobi_logo](https://cloud.githubusercontent.com/assets/2056885/7582290/b8d08b18-f894-11e4-9c8d-d9733e3e3a9c.png)
GDG Nairobi Logo

**Comment by profnandaa** [comment]
I think we needed a customized logo here, SolveforX, Nairobi?

**Comment by kenju254** [comment]
@ProfNandaa GDG There is one already... solve4x and also GDG Nairobi site is sufficient...

**Comment by profnandaa** [comment]
Good.

On Tue, May 12, 2015 at 5:39 PM, Kenneth Kinyanjui <notifications@github.com

> wrote:
> 
> @ProfNandaa https://github.com/ProfNandaa GDG There is one already...
> solve4x and also GDG Nairobi site is sufficient...
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/GDGKenya/Solve4X/issues/1#issuecomment-101303614.

## 

_Nandaa Anthony,_
_Software Architect, Serial Founder & Mentor.__Twitter/Github: *@profnandaa
http://twitter.com/profnandaa
*Blog: *www.nandaa.com http://nandaa.com
*Quick Links:_ labs.beyon.de | www.deveint.com | www.gdgnairobi.info

**Comment by kenju254** [comment]
@ProfNandaa is all right ...
